---
title: "CodeBook Project week 3"
author: "Elaine Ellerton"
date: "10/8/2019"
output: html_document
---

###Brief description of how the data was collected

The data came from 
The experiments were carried out with 30 volunteers ages 19-48. Subjects performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING)  while wearing a smartphone (Samsung Galaxy S II) on their waist. Data was collected using the phone's accelerometer and gyroscope. 3-axial linear accelerations and 3-axial angular velocities at a constant rate of 50Hz were recorded. The resulting data was randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

Pre-processing of sensor signals (accelerometer and gyroscope) was done by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, both gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force was filtered with 0.3 Hz cutoff frequency.  vector of features was obtained by calculating variables from the time and frequency domain.  

Time domain signals were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz.

###First data set description
Compiled from merging data sets from the [Human Activity Recognition Using Smartphones Data Set] ("http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones") and then only those with median or mean were selected

###Explanation of variables
These signals were used to estimate variables of the feature vector for each pattern:
'XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

TimeBodyAccelerometer.mean...XYZ                       
TimeGravityAccelerometer.mean...XYZ                     
TimeBodyAccelerometerJerk.mean...XYZ                  
TimeBodyGyroscope.mean...XYZ                          
TimeBodyGyroscopeJerk.mean...XYZ                      
TimeBodyAccelerometerMagnitude.mean..                 
TimeGravityAccelerometerMagnitude.mean..             
TimeBodyAccelerometerJerkMagnitude.mean..            
TimeBodyGyroscopeMagnitude.mean..                
TimeBodyGyroscopeJerkMagnitude.mean..                 
FrequencyBodyAccelerometer.mean...XYZ                  
FrequencyBodyAccelerometer.meanFreq...XYZ               
FrequencyBodyAccelerometerJerk.mean...XYZ              
FrequencyBodyAccelerometerJerk.meanFreq...XYZ           
FrequencyBodyGyroscope.mean...XYZ                       
FrequencyBodyGyroscope.meanFreq...XYZ                
FrequencyBodyAccelerometerMagnitude.mean..            
FrequencyBodyAccelerometerMagnitude.meanFreq..        
FrequencyBodyBodyAccelerometerJerkMagnitude.mean..    
FrequencyBodyBodyAccelerometerJerkMagnitude.meanFreq..
FrequencyBodyBodyGyroscopeMagnitude.mean.."            
FrequencyBodyBodyGyroscopeMagnitude.meanFreq..        
FrequencyBodyBodyGyroscopeJerkMagnitude.mean..        
FrequencyBodyBodyGyroscopeJerkMagnitude.meanFreq..    
angle.tBodyAccelerometerMean.gravity.                
angle.tBodyAccelerometerJerkMean..gravityMean       
angle.tBodyGyroscopeMean.gravityMean.                
angle.tBodyGyroscopeJerkMean.gravityMean.            
anglegravityMean XYZ                                 
TimeBodyAccelerometer.std...XYZ                         
TimeGravityAccelerometer.std...XYZ                     
TimeBodyAccelerometerJerk.std...XYZ                     
TimeBodyGyroscope.std...XYZ                             
TimeBodyGyroscopeJerk.std...XYZ                      
TimeBodyAccelerometerMagnitude.std..                 
TimeGravityAccelerometerMagnitude.std..              
TimeBodyAccelerometerJerkMagnitude.std..            
TimeBodyGyroscopeMagnitude.std.."                      
TimeBodyGyroscopeJerkMagnitude.std..                  
FrequencyBodyAccelerometer.std...XYZ                   
FrequencyBodyAccelerometerJerk.std...XYZ              
FrequencyBodyGyroscope.std...XYZ                      
FrequencyBodyAccelerometerMagnitude.std..       
FrequencyBodyBodyAccelerometerJerkMagnitude.std..   FrequencyBodyBodyGyroscopeMagnitude.std..       
FrequencyBodyBodyGyroscopeJerkMagnitude.std..


####Second data set is from taking the average of all the above variables for each activity and subject.
